
import type { Folder, Flashcard } from '@/lib/types';

export const defaultFolders: Folder[] = [
  // Salutations et vie sociale (niveau A1-A2)
  { id: '1', name: { fr: 'Salutations et vie sociale', es: 'Saludos y vida social' }, icon: '👋' },
  { id: '1.1', parentId: '1', name: { fr: 'Conversations basiques', es: 'Conversaciones básicas' }, icon: '💬' },
  { id: '1.2', parentId: '1', name: { fr: 'Présentations', es: 'Presentaciones' }, icon: '🙂' },
  { id: '1.3', parentId: '1', name: { fr: 'Émotions et sentiments', es: 'Emociones y sentimientos' }, icon: '😊' },
  
  // Nourriture et gastronomie
  { id: '2', name: { fr: 'Nourriture et gastronomie', es: 'Comida y gastronomía' }, icon: '🍽️' },
  { id: '2.1', parentId: '2', name: { fr: 'Fruits et légumes', es: 'Frutas y verduras' }, icon: '🍎' },
  { id: '2.2', parentId: '2', name: { fr: 'Boissons', es: 'Bebidas' }, icon: '☕' },
  { id: '2.3', parentId: '2', name: { fr: 'Repas et restaurants', es: 'Comidas y restaurantes' }, icon: '🍴' },
  { id: '2.4', parentId: '2', name: { fr: 'Cuisine et recettes', es: 'Cocina y recetas' }, icon: '👨‍🍳' },
  
  // Voyages et transports
  { id: '3', name: { fr: 'Voyages et transports', es: 'Viajes y transportes' }, icon: '✈️' },
  { id: '3.1', parentId: '3', name: { fr: 'Transports publics', es: 'Transportes públicos' }, icon: '🚆' },
  { id: '3.2', parentId: '3', name: { fr: 'Hébergement', es: 'Alojamiento' }, icon: '🏨' },
  { id: '3.3', parentId: '3', name: { fr: 'Tourisme et activités', es: 'Turismo y actividades' }, icon: '🏖️' },
  { id: '3.4', parentId: '3', name: { fr: 'Aéroport et douane', es: 'Aeropuerto y aduana' }, icon: '🛃' },
  
  // Maison et vie quotidienne
  { id: '4', name: { fr: 'Maison et vie quotidienne', es: 'Casa y vida cotidiana' }, icon: '🏠' },
  { id: '4.1', parentId: '4', name: { fr: 'Pièces de la maison', es: 'Habitaciones de la casa' }, icon: '🚪' },
  { id: '4.2', parentId: '4', name: { fr: 'Meubles et objets', es: 'Muebles y objetos' }, icon: '🛋️' },
  { id: '4.3', parentId: '4', name: { fr: 'Tâches ménagères', es: 'Tareas domésticas' }, icon: '🧹' },
  { id: '4.4', parentId: '4', name: { fr: 'Jardin et extérieur', es: 'Jardín y exterior' }, icon: '🌳' },
  
  // Nouveaux dossiers thématiques
  { id: '5', name: { fr: 'Travail et études', es: 'Trabajo y estudios' }, icon: '💼' },
  { id: '5.1', parentId: '5', name: { fr: 'Professions', es: 'Profesiones' }, icon: '👨‍🏫' },
  { id: '5.2', parentId: '5', name: { fr: 'Bureau et équipement', es: 'Oficina y equipamiento' }, icon: '💻' },
  { id: '5.3', parentId: '5', name: { fr: 'Réunions et présentations', es: 'Reuniones y presentaciones' }, icon: '📊' },
  
  { id: '6', name: { fr: 'Santé et bien-être', es: 'Salud y bienestar' }, icon: '❤️' },
  { id: '6.1', parentId: '6', name: { fr: 'Corps humain', es: 'Cuerpo humano' }, icon: '👤' },
  { id: '6.2', parentId: '6', name: { fr: 'Médecin et symptômes', es: 'Médico y síntomas' }, icon: '🏥' },
  { id: '6.3', parentId: '6', name: { fr: 'Sport et exercice', es: 'Deporte y ejercicio' }, icon: '⚽' },
  
  { id: '7', name: { fr: 'Culture et loisirs', es: 'Cultura y ocio' }, icon: '🎭' },
  { id: '7.1', parentId: '7', name: { fr: 'Arts et spectacles', es: 'Artes y espectáculos' }, icon: '🎨' },
  { id: '7.2', parentId: '7', name: { fr: 'Musique et instruments', es: 'Música e instrumentos' }, icon: '🎵' },
  { id: '7.3', parentId: '7', name: { fr: 'Lecture et médias', es: 'Lectura y medios' }, icon: '📚' }
];

export const defaultCards: Flashcard[] = [
  // === DOSSIER 1: Salutations et vie sociale ===
  // Conversations basiques (1.1)
  { id: 'c1.1.1', folderId: '1.1', fr: 'Bonjour', es: 'Hola', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.2', folderId: '1.1', fr: 'Comment allez-vous ?', es: '¿Cómo está usted?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.3', folderId: '1.1', fr: 'Très bien, merci', es: 'Muy bien, gracias', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.4', folderId: '1.1', fr: 'Et vous ?', es: '¿Y usted?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.5', folderId: '1.1', fr: 'Au revoir', es: 'Adiós', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.6', folderId: '1.1', fr: 'À bientôt', es: 'Hasta pronto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.7', folderId: '1.1', fr: 'S\'il vous plaît', es: 'Por favor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.8', folderId: '1.1', fr: 'Merci beaucoup', es: 'Muchas gracias', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.9', folderId: '1.1', fr: 'De rien', es: 'De nada', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.1.10', folderId: '1.1', fr: 'Excusez-moi', es: 'Disculpe', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Présentations (1.2)
  { id: 'c1.2.1', folderId: '1.2', fr: 'Je m\'appelle...', es: 'Me llamo...', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.2', folderId: '1.2', fr: 'Enchanté(e)', es: 'Encantado/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.3', folderId: '1.2', fr: 'Je viens de France', es: 'Soy de Francia', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.4', folderId: '1.2', fr: 'Quel âge avez-vous ?', es: '¿Cuántos años tiene?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.5', folderId: '1.2', fr: 'Je suis étudiant', es: 'Soy estudiante', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.6', folderId: '1.2', fr: 'Voici mon ami', es: 'Este es mi amigo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.7', folderId: '1.2', fr: 'Je suis ravi de vous rencontrer', es: 'Mucho gusto en conocerle', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.8', folderId: '1.2', fr: 'Comment vous appelez-vous ?', es: '¿Cómo se llama usted?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.9', folderId: '1.2', fr: 'D\'où venez-vous ?', es: '¿De dónde es usted?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.2.10', folderId: '1.2', fr: 'Que faites-vous dans la vie ?', es: '¿A qué se dedica?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Émotions et sentiments (1.3)
  { id: 'c1.3.1', folderId: '1.3', fr: 'Je suis heureux/heureuse', es: 'Estoy feliz/contento/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.2', folderId: '1.3', fr: 'Je suis triste', es: 'Estoy triste', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.3', folderId: '1.3', fr: 'Je suis fatigué(e)', es: 'Estoy cansado/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.4', folderId: '1.3', fr: 'Je suis en colère', es: 'Estoy enfadado/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.5', folderId: '1.3', fr: 'J\'ai peur', es: 'Tengo miedo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.6', folderId: '1.3', fr: 'Je suis surpris(e)', es: 'Estoy sorprendido/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.7', folderId: '1.3', fr: 'Je suis nerveux/nervouse', es: 'Estoy nervioso/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.8', folderId: '1.3', fr: 'Je suis calme', es: 'Estoy tranquilo/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.9', folderId: '1.3', fr: 'Je suis excité(e)', es: 'Estoy emocionado/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c1.3.10', folderId: '1.3', fr: 'Je suis inquiet/inquiète', es: 'Estoy preocupado/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // === DOSSIER 2: Nourriture et gastronomie ===
  // Fruits et légumes (2.1)
  { id: 'c2.1.1', folderId: '2.1', fr: 'Une pomme', es: 'Una manzana', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.2', folderId: '2.1', fr: 'Banane', es: 'Plátano', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.3', folderId: '2.1', fr: 'Orange', es: 'Naranja', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.4', folderId: '2.1', fr: 'Fraise', es: 'Fresa', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.5', folderId: '2.1', fr: 'Tomate', es: 'Tomate', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.6', folderId: '2.1', fr: 'Carotte', es: 'Zanahoria', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.7', folderId: '2.1', fr: 'Salade', es: 'Lechuga', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.8', folderId: '2.1', fr: 'Pomme de terre', es: 'Patata', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.9', folderId: '2.1', fr: 'Oignon', es: 'Cebolla', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.1.10', folderId: '2.1', fr: 'Poivron', es: 'Pimiento', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Boissons (2.2)
  { id: 'c2.2.1', folderId: '2.2', fr: 'Eau', es: 'Agua', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.2', folderId: '2.2', fr: 'Café', es: 'Café', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.3', folderId: '2.2', fr: 'Thé', es: 'Té', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.4', folderId: '2.2', fr: 'Lait', es: 'Leche', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.5', folderId: '2.2', fr: 'Jus d\'orange', es: 'Zumo de naranja', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.6', folderId: '2.2', fr: 'Vin rouge', es: 'Vino tinto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.7', folderId: '2.2', fr: 'Bière', es: 'Cerveza', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.8', folderId: '2.2', fr: 'Soda', es: 'Refresco', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.9', folderId: '2.2', fr: 'Chocolat chaud', es: 'Chocolate caliente', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.2.10', folderId: '2.2', fr: 'Cocktail', es: 'Cóctel', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Repas et restaurants (2.3)
  { id: 'c2.3.1', folderId: '2.3', fr: 'Le petit déjeuner', es: 'El desayuno', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.2', folderId: '2.3', fr: 'Le déjeuner', es: 'El almuerzo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.3', folderId: '2.3', fr: 'Le dîner', es: 'La cena', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.4', folderId: '2.3', fr: 'La carte, s\'il vous plaît', es: 'La carta, por favor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.5', folderId: '2.3', fr: 'L\'addition, s\'il vous plaît', es: 'La cuenta, por favor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.6', folderId: '2.3', fr: 'Je voudrais réserver une table', es: 'Me gustaría reservar una mesa', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.7', folderId: '2.3', fr: 'Je suis végétarien(ne)', es: 'Soy vegetariano/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.8', folderId: '2.3', fr: 'Je suis allergique aux noix', es: 'Soy alérgico/a a los frutos secos', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.9', folderId: '2.3', fr: 'C\'est délicieux !', es: '¡Está delicioso!', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.3.10', folderId: '2.3', fr: 'Le service est compris', es: 'El servicio está incluido', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Cuisine et recettes (2.4)
  { id: 'c2.4.1', folderId: '2.4', fr: 'Recette', es: 'Receta', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.2', folderId: '2.4', fr: 'Cuillère', es: 'Cuchara', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.3', folderId: '2.4', fr: 'Couteau', es: 'Cuchillo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.4', folderId: '2.4', fr: 'Fourchette', es: 'Tenedor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.5', folderId: '2.4', fr: 'Casserole', es: 'Cacerola', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.6', folderId: '2.4', fr: 'Poêle à frire', es: 'Sartén', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.7', folderId: '2.4', fr: 'Four', es: 'Horno', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.8', folderId: '2.4', fr: 'Cuire au four', es: 'Hornear', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.9', folderId: '2.4', fr: 'Faire bouillir', es: 'Hervir', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.10', folderId: '2.4', fr: 'Mélanger', es: 'Mezclar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.11', folderId: '2.4', fr: 'Recette de cuisine', es: 'Receta de cocina', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.12', folderId: '2.4', fr: 'Ingrédients', es: 'Ingredientes', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.13', folderId: '2.4', fr: 'Éplucher', es: 'Pelar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.14', folderId: '2.4', fr: 'Couper en dés', es: 'Cortar en dados', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.15', folderId: '2.4', fr: 'Hacher', es: 'Picar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.16', folderId: '2.4', fr: 'Émincer', es: 'Filetear', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.17', folderId: '2.4', fr: 'Frire', es: 'Freír', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.18', folderId: '2.4', fr: 'Sauter', es: 'Saltear', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.19', folderId: '2.4', fr: 'Griller', es: 'Asar a la parrilla', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.20', folderId: '2.4', fr: 'Cuire à la vapeur', es: 'Cocer al vapor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.21', folderId: '2.4', fr: 'Mariner', es: 'Marinar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.22', folderId: '2.4', fr: 'Assaisonner', es: 'Aliñar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.23', folderId: '2.4', fr: 'Saler', es: 'Salar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.24', folderId: '2.4', fr: 'Poivrer', es: 'Pimentar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.25', folderId: '2.4', fr: 'Mesures', es: 'Medidas', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.26', folderId: '2.4', fr: 'Cuillère à soupe', es: 'Cucharada', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.27', folderId: '2.4', fr: 'Cuillère à café', es: 'Cucharadita', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.28', folderId: '2.4', fr: 'Verre doseur', es: 'Vaso medidor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.29', folderId: '2.4', fr: 'Balance de cuisine', es: 'Báscula de cocina', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.30', folderId: '2.4', fr: 'Temps de cuisson', es: 'Tiempo de cocción', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.31', folderId: '2.4', fr: 'Fouet de cuisine', es: 'Batidor de cocina', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.32', folderId: '2.4', fr: 'Planche à découper', es: 'Tabla de cortar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.33', folderId: '2.4', fr: 'Râpe', es: 'Rallador', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.34', folderId: '2.4', fr: 'Passoire', es: 'Colador', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.35', folderId: '2.4', fr: 'Marmite', es: 'Olla grande', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.36', folderId: '2.4', fr: 'Cuisson al dente', es: 'Cocción al dente', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.37', folderId: '2.4', fr: 'Réduire (une sauce)', es: 'Reducir (una salsa)', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.38', folderId: '2.4', fr: 'Déglacer', es: 'Desglasar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.39', folderId: '2.4', fr: 'Bain-marie', es: 'Baño María', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.40', folderId: '2.4', fr: 'Cuisson à l\'étouffée', es: 'Cocción a fuego lento', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.41', folderId: '2.4', fr: 'Feu vif', es: 'Fuego fuerte', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.42', folderId: '2.4', fr: 'Feu doux', es: 'Fuego lento', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.43', folderId: '2.4', fr: 'Préchauffer le four', es: 'Precalentar el horno', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.44', folderId: '2.4', fr: 'Cuisson à point', es: 'Cocción al punto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.45', folderId: '2.4', fr: 'Saisir la viande', es: 'Sellar la carne', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.46', folderId: '2.4', fr: 'Rectifier l\'assaisonnement', es: 'Rectificar el aliño', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.47', folderId: '2.4', fr: 'Dresser l\'assiette', es: 'Presentar el plato', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.48', folderId: '2.4', fr: 'Garniture', es: 'Guarnición', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.49', folderId: '2.4', fr: 'Décoration culinaire', es: 'Decoración culinaria', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c2.4.50', folderId: '2.4', fr: 'Couvercle', es: 'Tapa', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

// === DOSSIER 3: Voyages et transports ===
  // Transports publics (3.1)
  { id: 'c3.1.1', folderId: '3.1', fr: 'Où est la gare ?', es: '¿Dónde está la estación?', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.2', folderId: '3.1', fr: 'Un billet pour Madrid, s\'il vous plaît', es: 'Un billete para Madrid, por favor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.3', folderId: '3.1', fr: 'Le prochain train', es: 'El próximo tren', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.4', folderId: '3.1', fr: 'Arrêt de bus', es: 'Parada de autobús', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.5', folderId: '3.1', fr: 'Métro', es: 'Metro', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.6', folderId: '3.1', fr: 'Taxi', es: 'Taxi', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.7', folderId: '3.1', fr: 'Aéroport', es: 'Aeropuerto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.8', folderId: '3.1', fr: 'Quai', es: 'Andén', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.9', folderId: '3.1', fr: 'Horaires', es: 'Horarios', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.1.10', folderId: '3.1', fr: 'Compagnie aérienne', es: 'Aerolínea', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Hébergement (3.2)
  { id: 'c3.2.1', folderId: '3.2', fr: 'Hôtel', es: 'Hotel', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.2', folderId: '3.2', fr: 'Chambre simple', es: 'Habitación individual', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.3', folderId: '3.2', fr: 'Chambre double', es: 'Habitación doble', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.4', folderId: '3.2', fr: 'Réception', es: 'Recepción', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.5', folderId: '3.2', fr: 'Clé', es: 'Llave', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.6', folderId: '3.2', fr: 'Petit déjeuner inclus', es: 'Desayuno incluido', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.7', folderId: '3.2', fr: 'Ascenseur', es: 'Ascensor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.8', folderId: '3.2', fr: 'Wi-Fi gratuit', es: 'Wi-Fi gratuito', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.9', folderId: '3.2', fr: 'Annulation', es: 'Cancelación', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.2.10', folderId: '3.2', fr: 'Service en chambre', es: 'Servicio a la habitación', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Tourisme et activités (3.3)
  { id: 'c3.3.1', folderId: '3.3', fr: 'La plage', es: 'La playa', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.2', folderId: '3.3', fr: 'Montagne', es: 'Montaña', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.3', folderId: '3.3', fr: 'Visite guidée', es: 'Visita guiada', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.4', folderId: '3.3', fr: 'Guide touristique', es: 'Guía turístico', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.5', folderId: '3.3', fr: 'Carte touristique', es: 'Mapa turístico', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.6', folderId: '3.3', fr: 'Monument', es: 'Monumento', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.7', folderId: '3.3', fr: 'Excursion', es: 'Excursión', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.8', folderId: '3.3', fr: 'Randonnée', es: 'Senderismo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.9', folderId: '3.3', fr: 'Plongée sous-marine', es: 'Buceo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.3.10', folderId: '3.3', fr: 'Ski', es: 'Esquí', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Aéroport et douane (3.4)
  { id: 'c3.4.1', folderId: '3.4', fr: 'Passeport', es: 'Pasaporte', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.2', folderId: '3.4', fr: 'Carte d\'embarquement', es: 'Tarjeta de embarque', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.3', folderId: '3.4', fr: 'Contrôle de sécurité', es: 'Control de seguridad', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.4', folderId: '3.4', fr: 'Douane', es: 'Aduana', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.5', folderId: '3.4', fr: 'Bagage à main', es: 'Equipaje de mano', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.6', folderId: '3.4', fr: 'Bagage en soute', es: 'Equipaje facturado', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.7', folderId: '3.4', fr: 'Porte d\'embarquement', es: 'Puerta de embarque', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.8', folderId: '3.4', fr: 'Retrait des bagages', es: 'Recogida de equipaje', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.9', folderId: '3.4', fr: 'Déclaration douanière', es: 'Declaración de aduana', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c3.4.10', folderId: '3.4', fr: 'Vol en correspondance', es: 'Vuelo de conexión', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

// === DOSSIER 4: Maison et vie quotidienne ===
  // Pièces de la maison (4.1)
  { id: 'c4.1.1', folderId: '4.1', fr: 'Cuisine', es: 'Cocina', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.2', folderId: '4.1', fr: 'Salon', es: 'Salón', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.3', folderId: '4.1', fr: 'Chambre', es: 'Dormitorio', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.4', folderId: '4.1', fr: 'Salle de bain', es: 'Baño', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.5', folderId: '4.1', fr: 'Toilettes', es: 'Aseo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.6', folderId: '4.1', fr: 'Bureau', es: 'Despacho', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.7', folderId: '4.1', fr: 'Salle à manger', es: 'Comedor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.8', folderId: '4.1', fr: 'Couloir', es: 'Pasillo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.9', folderId: '4.1', fr: 'Grenier', es: 'Ático', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.1.10', folderId: '4.1', fr: 'Cave', es: 'Sótano', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Meubles et objets (4.2)
  { id: 'c4.2.1', folderId: '4.2', fr: 'Table', es: 'Mesa', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.2', folderId: '4.2', fr: 'Chaise', es: 'Silla', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.3', folderId: '4.2', fr: 'Lit', es: 'Cama', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.4', folderId: '4.2', fr: 'Armoire', es: 'Armario', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.5', folderId: '4.2', fr: 'Canapé', es: 'Sofá', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.6', folderId: '4.2', fr: 'Étagère', es: 'Estantería', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.7', folderId: '4.2', fr: 'Lampe', es: 'Lámpara', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.8', folderId: '4.2', fr: 'Télévision', es: 'Televisión', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.9', folderId: '4.2', fr: 'Radiateur', es: 'Radiador', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.2.10', folderId: '4.2', fr: 'Miroir', es: 'Espejo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Tâches ménagères (4.3)
  { id: 'c4.3.1', folderId: '4.3', fr: 'Nettoyer', es: 'Limpiar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.2', folderId: '4.3', fr: 'Aspirateur', es: 'Aspiradora', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.3', folderId: '4.3', fr: 'Balai', es: 'Escoba', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.4', folderId: '4.3', fr: 'Serpillière', es: 'Fregona', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.5', folderId: '4.3', fr: 'Laver la vaisselle', es: 'Lavar los platos', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.6', folderId: '4.3', fr: 'Faire la lessive', es: 'Hacer la colada', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.7', folderId: '4.3', fr: 'Repasser', es: 'Planchar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.8', folderId: '4.3', fr: 'Ranger', es: 'Ordenar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.9', folderId: '4.3', fr: 'Dépoussiérer', es: 'Desempolvar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.3.10', folderId: '4.3', fr: 'Sortir les poubelles', es: 'Sacar la basura', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // Jardin et extérieur (4.4)
  { id: 'c4.4.1', folderId: '4.4', fr: 'Jardin', es: 'Jardín', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.2', folderId: '4.4', fr: 'Fleur', es: 'Flor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.3', folderId: '4.4', fr: 'Arbre', es: 'Árbol', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.4', folderId: '4.4', fr: 'Pelouse', es: 'Césped', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.5', folderId: '4.4', fr: 'Arroser les plantes', es: 'Regar las plantas', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.6', folderId: '4.4', fr: 'Tondre la pelouse', es: 'Cortar el césped', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.7', folderId: '4.4', fr: 'Balcon', es: 'Balcón', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.8', folderId: '4.4', fr: 'Terrasse', es: 'Terraza', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.9', folderId: '4.4', fr: 'Piscine', es: 'Piscina', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c4.4.10', folderId: '4.4', fr: 'Barbecue', es: 'Barbacoa', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // === DOSSIER 5: Travail et études ===
  // Professions (5.1)
  { id: 'c5.1.1', folderId: '5.1', fr: 'Médecin', es: 'Médico', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.2', folderId: '5.1', fr: 'Enseignant', es: 'Profesor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.3', folderId: '5.1', fr: 'Ingénieur', es: 'Ingeniero', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.4', folderId: '5.1', fr: 'Avocat', es: 'Abogado', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.5', folderId: '5.1', fr: 'Artiste', es: 'Artista', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.6', folderId: '5.1', fr: 'Comptable', es: 'Contable', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.7', folderId: '5.1', fr: 'Secrétaire', es: 'Secretario/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.8', folderId: '5.1', fr: 'Vendeur/Vendeuse', es: 'Vendedor/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.9', folderId: '5.1', fr: 'Chef cuisinier', es: 'Chef de cocina', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.1.10', folderId: '5.1', fr: 'Architecte', es: 'Arquitecto/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Bureau et équipement (5.2)
  { id: 'c5.2.1', folderId: '5.2', fr: 'Ordinateur', es: 'Ordenador', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.2', folderId: '5.2', fr: 'Imprimante', es: 'Impresora', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.3', folderId: '5.2', fr: 'Clavier', es: 'Teclado', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.4', folderId: '5.2', fr: 'Souris', es: 'Ratón', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.5', folderId: '5.2', fr: 'Écran', es: 'Pantalla', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.6', folderId: '5.2', fr: 'Téléphone', es: 'Teléfono', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.7', folderId: '5.2', fr: 'Agenda', es: 'Agenda', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.8', folderId: '5.2', fr: 'Classeur', es: 'Carpeta', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.9', folderId: '5.2', fr: 'Stylo', es: 'Bolígrafo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.2.10', folderId: '5.2', fr: 'Papier', es: 'Papel', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // Réunions et présentations (5.3)
  { id: 'c5.3.1', folderId: '5.3', fr: 'Réunion', es: 'Reunión', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.2', folderId: '5.3', fr: 'Présentation', es: 'Presentación', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.3', folderId: '5.3', fr: 'Ordre du jour', es: 'Orden del día', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.4', folderId: '5.3', fr: 'Présenter un projet', es: 'Presentar un proyecto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.5', folderId: '5.3', fr: 'Prendre des notes', es: 'Tomar apuntes', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.6', folderId: '5.3', fr: 'Point de vue', es: 'Punto de vista', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.7', folderId: '5.3', fr: 'Décision', es: 'Decisión', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.8', folderId: '5.3', fr: 'Rapport', es: 'Informe', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.9', folderId: '5.3', fr: 'Délai', es: 'Plazo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c5.3.10', folderId: '5.3', fr: 'Objectif', es: 'Objetivo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // === DOSSIER 6: Santé et bien-être ===
  // Corps humain (6.1)
  { id: 'c6.1.1', folderId: '6.1', fr: 'Tête', es: 'Cabeza', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.2', folderId: '6.1', fr: 'Main', es: 'Mano', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.3', folderId: '6.1', fr: 'Pied', es: 'Pie', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.4', folderId: '6.1', fr: 'Dos', es: 'Espalda', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.5', folderId: '6.1', fr: 'Cœur', es: 'Corazón', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.6', folderId: '6.1', fr: 'Estomac', es: 'Estómago', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.7', folderId: '6.1', fr: 'Yeux', es: 'Ojos', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.8', folderId: '6.1', fr: 'Oreille', es: 'Oído', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.9', folderId: '6.1', fr: 'Nez', es: 'Nariz', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.1.10', folderId: '6.1', fr: 'Bouche', es: 'Boca', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  
  // Médecin et symptômes (6.2)
  { id: 'c6.2.1', folderId: '6.2', fr: 'Docteur', es: 'Doctor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.2', folderId: '6.2', fr: 'Infirmier/Infirmière', es: 'Enfermero/a', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.3', folderId: '6.2', fr: 'J\'ai mal à la tête', es: 'Me duele la cabeza', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.4', folderId: '6.2', fr: 'Fièvre', es: 'Fiebre', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.5', folderId: '6.2', fr: 'Toux', es: 'Tos', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.6', folderId: '6.2', fr: 'Rhume', es: 'Resfriado', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.7', folderId: '6.2', fr: 'Nausée', es: 'Náusea', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.8', folderId: '6.2', fr: 'Vertige', es: 'Vértigo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.9', folderId: '6.2', fr: 'Blessure', es: 'Lesión', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.2.10', folderId: '6.2', fr: 'Ordonnance', es: 'Receta médica', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // Sport et exercice (6.3)
  { id: 'c6.3.1', folderId: '6.3', fr: 'Sport', es: 'Deporte', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.2', folderId: '6.3', fr: 'Football', es: 'Fútbol', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.3', folderId: '6.3', fr: 'Basketball', es: 'Baloncesto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.4', folderId: '6.3', fr: 'Natation', es: 'Natación', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.5', folderId: '6.3', fr: 'Course à pied', es: 'Correr', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.6', folderId: '6.3', fr: 'Vélo', es: 'Bicicleta', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.7', folderId: '6.3', fr: 'Musculation', es: 'Culturismo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.8', folderId: '6.3', fr: 'Équipe', es: 'Equipo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.9', folderId: '6.3', fr: 'Entraînement', es: 'Entrenamiento', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c6.3.10', folderId: '6.3', fr: 'Compétition', es: 'Competición', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // === DOSSIER 7: Culture et loisirs ===
  // Arts et spectacles (7.1)
  { id: 'c7.1.1', folderId: '7.1', fr: 'Cinéma', es: 'Cine', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.2', folderId: '7.1', fr: 'Théâtre', es: 'Teatro', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.3', folderId: '7.1', fr: 'Musée', es: 'Museo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.4', folderId: '7.1', fr: 'Concert', es: 'Concierto', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.5', folderId: '7.1', fr: 'Exposition', es: 'Exposición', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.6', folderId: '7.1', fr: 'Danse', es: 'Baile', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.7', folderId: '7.1', fr: 'Peinture', es: 'Pintura', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.8', folderId: '7.1', fr: 'Sculpture', es: 'Escultura', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.9', folderId: '7.1', fr: 'Photographie', es: 'Fotografía', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.1.10', folderId: '7.1', fr: 'Livre', es: 'Libro', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // Musique et instruments (7.2)
  { id: 'c7.2.1', folderId: '7.2', fr: 'Musique', es: 'Música', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.2', folderId: '7.2', fr: 'Guitare', es: 'Guitarra', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.3', folderId: '7.2', fr: 'Piano', es: 'Piano', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.4', folderId: '7.2', fr: 'Violon', es: 'Violín', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.5', folderId: '7.2', fr: 'Batterie', es: 'Batería', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.6', folderId: '7.2', fr: 'Chanter', es: 'Cantar', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.7', folderId: '7.2', fr: 'Chanson', es: 'Canción', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.8', folderId: '7.2', fr: 'Orchestre', es: 'Orquesta', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.9', folderId: '7.2', fr: 'Note musicale', es: 'Nota musical', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.2.10', folderId: '7.2', fr: 'Mélodie', es: 'Melodía', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },

  // Lecture et médias (7.3)
  { id: 'c7.3.1', folderId: '7.3', fr: 'Lire', es: 'Leer', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.2', folderId: '7.3', fr: 'Journal', es: 'Periódico', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.3', folderId: '7.3', fr: 'Magazine', es: 'Revista', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.4', folderId: '7.3', fr: 'Roman', es: 'Novela', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.5', folderId: '7.3', fr: 'Bibliothèque', es: 'Biblioteca', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.6', folderId: '7.3', fr: 'Internet', es: 'Internet', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.7', folderId: '7.3', fr: 'Réseaux sociaux', es: 'Redes sociales', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.8', folderId: '7.3', fr: 'Actualités', es: 'Noticias', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.9', folderId: '7.3', fr: 'Article', es: 'Artículo', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
  { id: 'c7.3.10', folderId: '7.3', fr: 'Auteur', es: 'Autor', nextReview: Date.now(), interval: 0, easeFactor: 2.5, repetition: 0, status: 'new' },
];
